const translations = {
  en: {
    "menu-text": "Menu",
    "nav-home": "Home",
    "nav-about": "About",
    "nav-buy": "Buy",
    "nav-feedback": "Feedback",
    "nav-account": "Account",
    "nav-settings": "Settings",
    "nav-logout": "LogOut",
    "nav-signin": "SignIn",
    "discover-text": "Discover The<br>Beauty Within",
    "view-collection": "View collection",
    "skincare-header": "Natural and<br>certified organic",
    "skincare-title": "Skincare",
    "skincare-desc": "Experience gentle and effective skincare solutions that respect your skin and the planet.",
    "skincare-shop": "Shop all",
    "products-header": "Products",
    "products-sub": "Healthy skin, wildly you",
    "feature-header": "Feature",
    "feature-text": "Innovation-led<br>Products",
    "feature-info": "Our featured products are crafted using advanced skincare technology, combining nature with science to deliver real, visible results.",
    "read-more": "Read more",
    "companies-text": "“We partner with trusted brands to bring you premium quality skincare products that are clean, effective, and ethical.”",
    "body-wash": "Body Wash",
    "face-wash": "Face wash",
    "cleanser": "Cleanser",
    "skinn-blog-header": "Skinn blog",
    "blog-text-1": "Which skinceuticals vitamin c serum is right for you",
    "scroll-top": "↑",
    "footer-wise": "The wise man therefore always holds in these matters to this principle",
    "footer-designed": "Designed by <a class=\"footer__link\">Webestica</a>",
    "footer-powered": "Powered by <a class=\"footer__link\">Webflow</a>",
    "footer-pages-header": "Pages",
    "footer-page-home": "Home",
    "footer-page-home2": "Home 2",
    "footer-page-shop-all": "Shop All",
    "footer-page-our-story": "Our Story",
    "footer-page-blog": "Blog",
    "footer-page-faqs": "FAQs",
    "footer-page-contact-us": "Contact Us",
    "footer-page-instructions": "Instructions",
    "footer-page-style-guide": "Style Guide",
    "footer-page-licenses": "Licenses",
    "footer-page-changelog": "Changelog",
    "footer-contact-header": "Contact us",
    "footer-contact-question": "Have questions or suggestions?",
    "footer-contact-email": "hello@webestica.com",
    "footer-contact-assistance": "Need assistance? Give us a call.",
    "footer-contact-phone": "+01 598 269 4756",
    "footer-support-header": "We’re here for you",
    "footer-schedule-mon-thu": "Monday - Thursday: 9:30 - 18:00",
    "footer-schedule-fri": "Friday: 9:30 - 15:00",
    "page-leader-title": "We are the leaders in sales since 2025",
    "page-leader-desc": "Our store is one of the best solutions!",
    "page-location-title": "Where are we located?",
    "product-manage-title": "Product Management",
    "product-select-default": "Select a product",
    "product-field-name": "Name",
    "product-field-category": "Category",
    "product-field-price": "Price",
    "product-field-material": "Material",
    "product-field-style": "Style",
    "product-field-description": "Description",
    "product-field-photo": "Image URL",
    "product-field-instock": "In Stock",
    "product-btn-add": "Add",
    "product-btn-update": "Update",
    "product-btn-delete": "Delete",
    "admin-feedback-all-users": "All users",
    "admin-feedback-all-products": "All products",
    "admin-feedback-delete": "Delete",
    "not-authorized": "User is not authorized",
    "form-firstname": "First Name",
    "form-phone": "Phone",
    "form-email": "Email",
    "form-nickname": "Nickname",
    "form-password": "Password",
    "btn-update": "Update",
    "btn-delete": "Reset settings",
    "feedback-placeholder": "Your feedback...",
    "btn-send": "Send",
    "signin-title": "Sign in",
    "signup-title": "Sign up",
    "placeholder-username": "Username",
    "placeholder-password": "Password",
    "placeholder-repeat-password": "Repeat Password",
    "placeholder-firstname": "First Name*",
    "placeholder-lastname": "Last Name*",
    "placeholder-middlename": "Middle Name (optional)",
    "placeholder-phone": "Phone (+375...)*",
    "placeholder-email": "Email*",
    "placeholder-nickname": "Nickname",
    "placeholder-generated-password": "Generated Password",
    "btn-login": "Login",
    "btn-signup": "Sign up",
    "btn-regen-nickname": "↻",
    "btn-generate-password": "Generate",
    "btn-goto-signup": "Sign up",
    "btn-goto-signin": "Sign in",
    "option-manual": "Enter password",
    "option-auto": "Auto-generate password",
    "terms-text": "I agree to the <span id='agreement'>User Agreement</span>*",
    "left-panel-title": "New here?",
    "left-panel-text": "Register now and join our awesome community!",
    "right-panel-title": "One of us?",
    "right-panel-text": "Log in and continue your journey.",
    "catalog-title": "Catalog",
    "favorites": "Favorites",
    "cart": "Cart",
    "search-placeholder": "Search",
    "sort-default": "Sort by",
    "sort-name": "Name",
    "sort-price-asc": "Price (↑)",
    "sort-style": "Style",
    "category-default": "Category",
    "category-furniture": "Furniture",
    "category-lighting": "Lighting",
    "category-decor": "Decor",
    "btn-reset": "Reset",
    "btn-sort-name": "Sort by Name (A-Z)",
    "btn-sort-price-asc": "Sort by Price (↑)",
    "btn-sort-price-desc": "Sort by Price (↓)",
    "btn-filter-expensive": "Expensive items (>50,000₽)",
    "btn-filter-cheap": "Cheap items (>10,000₽)",
    "btn-filter-instock": "In Stock Only",
    "label-name": "Name",
    "label-category": "Category",
    "label-price": "Price",
    "label-material": "Material",
    "label-description": "Description",
    "label-instock": "In Stock",
    "shop": "Shop now"
  },
  ru: {
    "menu-text": "Меню",
    "nav-home": "Главная",
    "nav-about": "О нас",
    "nav-buy": "Купить",
    "nav-feedback": "Отзывы",
    "nav-account": "Аккаунт",
    "nav-settings": "Настройки",
    "nav-logout": "Выйти",
    "nav-signin": "Войти",
    "discover-text": "Откройте<br>внутреннюю красоту",
    "view-collection": "Посмотреть коллекцию",
    "skincare-header": "Натуральный и<br>сертифицированный",
    "skincare-title": "Уход",
    "skincare-desc": "Ощутите мягкий и эффективный уход, уважающий вашу кожу и природу.",
    "skincare-shop": "Купить всё",
    "products-header": "Продукты",
    "products-sub": "Здоровая кожа — настоящее вы",
    "feature-header": "Особенности",
    "feature-text": "Инновационные<br>продукты",
    "feature-info": "Наши продукты создаются с использованием передовых технологий ухода за кожей, сочетая природу и науку для получения видимых результатов.",
    "read-more": "Читать далее",
    "companies-text": "«Мы сотрудничаем с проверенными брендами, чтобы предложить вам качественные, чистые и этичные средства по уходу за кожей.»",
    "body-wash": "Гель для душа",
    "face-wash": "Умывание для лица",
    "cleanser": "Очищающее средство",
    "skinn-blog-header": "Блог Skinn",
    "blog-text-1": "Какой витамин C от Skinceuticals подойдет именно вам",
    "scroll-top": "↑",
    "footer-wise": "Мудрый человек всегда придерживается этого принципа в подобных вопросах",
    "footer-designed": "Дизайн от <a class=\"footer__link\">Webestica</a>",
    "footer-powered": "Работает на <a class=\"footer__link\">Webflow</a>",
    "footer-pages-header": "Страницы",
    "footer-page-home": "Главная",
    "footer-page-home2": "Главная 2",
    "footer-page-shop-all": "Магазин",
    "footer-page-our-story": "Наша история",
    "footer-page-blog": "Блог",
    "footer-page-faqs": "Вопросы",
    "footer-page-contact-us": "Связаться с нами",
    "footer-page-instructions": "Инструкции",
    "footer-page-style-guide": "Стиль",
    "footer-page-licenses": "Лицензии",
    "footer-page-changelog": "Изменения",
    "footer-contact-header": "Контакты",
    "footer-contact-question": "Есть вопросы или предложения?",
    "footer-contact-email": "hello@webestica.com",
    "footer-contact-assistance": "Нужна помощь? Позвоните нам.",
    "footer-contact-phone": "+01 598 269 4756",
    "footer-support-header": "Мы здесь для вас",
    "footer-schedule-mon-thu": "Понедельник - Четверг: 9:30 - 18:00",
    "footer-schedule-fri": "Пятница: 9:30 - 15:00",
    "page-leader-title": "Мы лидеры продаж с 2025 года",
    "page-leader-desc": "Наш магазин — одно из лучших решений!",
    "page-location-title": "Где мы находимся?",
    "product-manage-title": "Управление товарами",
    "product-select-default": "Выберите товар",
    "product-field-name": "Название",
    "product-field-category": "Категория",
    "product-field-price": "Цена",
    "product-field-material": "Материал",
    "product-field-style": "Стиль",
    "product-field-description": "Описание",
    "product-field-photo": "Ссылка на изображение",
    "product-field-instock": "В наличии",
    "product-btn-add": "Добавить",
    "product-btn-update": "Обновить",
    "product-btn-delete": "Удалить",
    "admin-feedback-all-users": "Все пользователи",
    "admin-feedback-all-products": "Все товары",
    "admin-feedback-delete": "Удалить",
    "not-authorized": "Пользователь не авторизован",
    "form-firstname": "Имя",
    "form-phone": "Телефон",
    "form-email": "Email",
    "form-nickname": "Никнейм",
    "form-password": "Пароль",
    "btn-update": "Обновить",
    "btn-delete": "Сброс настроек",
    "feedback-placeholder": "Ваш отзыв...",
    "btn-send": "Отправить",
    "signin-title": "Вход",
    "signup-title": "Регистрация",
    "placeholder-username": "Имя пользователя",
    "placeholder-password": "Пароль",
    "placeholder-repeat-password": "Повторите пароль",
    "placeholder-firstname": "Имя*",
    "placeholder-lastname": "Фамилия*",
    "placeholder-middlename": "Отчество (необязательно)",
    "placeholder-phone": "Телефон (+375...)*",
    "placeholder-email": "Email*",
    "placeholder-nickname": "Никнейм",
    "placeholder-generated-password": "Сгенерированный пароль",
    "btn-login": "Войти",
    "btn-signup": "Зарегистрироваться",
    "btn-regen-nickname": "↻",
    "btn-generate-password": "Сгенерировать",
    "btn-goto-signup": "Регистрация",
    "btn-goto-signin": "Вход",
    "option-manual": "Ввести пароль",
    "option-auto": "Сгенерировать пароль",
    "terms-text": "Я принимаю <span id='agreement'>пользовательское соглашение</span>*",
    "left-panel-title": "Впервые у нас?",
    "left-panel-text": "Создайте аккаунт и присоединяйтесь к нашему сообществу!",
    "right-panel-title": "Уже с нами?",
    "right-panel-text": "Войдите в систему и продолжайте пользоваться сервисом.",
    "catalog-title": "Каталог",
    "favorites": "Избранное",
    "cart": "Корзина",
    "search-placeholder": "Искать",
    "sort-default": "Сортировать по",
    "sort-name": "Название",
    "sort-price-asc": "Цена(↑)",
    "sort-style": "Стиль",
    "category-default": "Категория",
    "category-furniture": "Мебель",
    "category-lighting": "Освещение",
    "category-decor": "Декор",
    "btn-reset": "Сбросить",
    "btn-sort-name": "Сортировать по названию (A-Z)",
    "btn-sort-price-asc": "Сортировать по цене (↑)",
    "btn-sort-price-desc": "Сортировать по цене (↓)",
    "btn-filter-expensive": "Дорогие товары (>50,000₽)",
    "btn-filter-cheap": "Дешевые товары (>10,000₽)",
    "btn-filter-instock": "Только в наличии",
    "label-name": "Имя",
    "label-category": "Категория",
    "label-price": "Цена",
    "label-material": "Материал",
    "label-description": "Описание",
    "label-instock": "Наличие",
    "shop": "Купить"
  }
};

function getTranslate(lang) {
  const elements = document.querySelectorAll("[data-i18n]");
  elements.forEach(el => {
    const key = el.dataset.i18n;
    const translated = translations[lang][key];
    if (translated) {
      el.innerHTML = translated;
    }
  });

  if (lang === "ru" && window.innerWidth <= 700) {
    import('./styles/main/main-ru.scss');
  }

  localStorage.setItem("lang", lang);

  document.querySelectorAll('.language-switcher button').forEach(btn => {
    btn.classList.toggle('active-lang', btn.dataset.lang === lang);
  });
}


document.addEventListener("DOMContentLoaded", () => {
  const savedLang = localStorage.getItem('lang') || 'en';
  getTranslate(savedLang);

  const switcher = document.querySelector('.language-switcher');
  if (switcher) {
    switcher.addEventListener('click', (event) => {
      const btn = event.target.closest('button[data-lang]');
      if (btn) {
        const lang = btn.getAttribute('data-lang');
        getTranslate(lang);
      }
    });
  }
});